//Dummy example for positive polarity rule file

package rules.positive.userFiles;

import ceu.biolab.cmm.shared.dto.FeatureAnnotation.AnnotatedFeature;
import ceu.biolab.cmm.shared.dto.FeatureAnnotation.ResultItem;
import ceu.biolab.cmm.shared.domain.MobilePhases;
import java.util.List;

// Declare the global list
global AnnotatedFeature lipid;
global List mobilePhases;
global String sampleType;

// =======================================
// RULE TYPE 1: Positive presence
// Check that specific adducts appear
// =======================================
rule "Dummy_Positive - Presence [M+H]+"
when
    $adduct: ResultItem(adductName == "[M+H]+")
    // This checks whether the biological matrix is what's expected
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "Dummy_Positive - Presence [M+Na]+"
when
    $adduct: ResultItem(adductName == "[M+Na]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+Na]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

// =======================================
// RULE TYPE 2: Negative presence (absence)
// Check if most intense adduct does NOT appear
// =======================================
rule "Dummy_Positive - No presence [M+H]+"
when
    not ResultItem(adductName == "[M+H]+")
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+H]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

// =======================================
// RULE TYPE 3: Correct intensity order
// Adduct1 intensity > Adduct2 intensity
// =======================================
rule "Dummy_Positive - Intensity [M+H]+ > [M+Na]+"
when
    $adduct1: ResultItem(adductName == "[M+H]+")
    $adduct2: ResultItem(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+H]+ > [M+Na]+, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

// =======================================
// RULE TYPE 4: Incorrect intensity order
// Adduct1 intensity < Adduct2 intensity
// =======================================
rule "Dummy_Positive - Intensity [M+H]+ < [M+Na]+"
when
    $adduct1: ResultItem(adductName == "[M+H]+")
    $adduct2: ResultItem(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+H]+ < [M+Na]+, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end