package rules.negative;
import ceu.biolab.cmm.shared.dto.FeatureAnnotation.AnnotatedFeature;
import ceu.biolab.cmm.shared.dto.FeatureAnnotation.ResultItem;
import ceu.biolab.cmm.shared.domain.MobilePhases;
 
import java.util.List;

// Declare the global list
global AnnotatedFeature lipid;
global List mobilePhases;
global String sampleType;


 rule "LPI_NegativeCheck - Presence [M-H]-"
 when
     $adduct: ResultItem(adductName == "[M-H]-")
      eval(sampleType.equalsIgnoreCase("PLASMA"))
 then
     
     lipid.setScore(1);
     lipid.setDescrCorrect("Contains [M-H]-, ");
     lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
 end
  rule "LPI_NegativeCheck - No presence [M-H]-"
  when
      not ResultItem(adductName == "[M-H]-")
       eval(sampleType.equalsIgnoreCase("PLASMA"))
  then

      lipid.setScore(-1);
      lipid.setDescrIncorrect("Missing [M-H]-, ");
      lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
  end

 rule "LPI_NegativeCheck - Presence [M-H+(CH3COONa)]-"
 when
     $adduct: ResultItem(adductName == "[M-H+(CH3COONa)]-")
     $phase1 : MobilePhases() from mobilePhases
      eval($phase1 == MobilePhases.CH3COO)
       eval(sampleType.equalsIgnoreCase("PLASMA"))
 then
     
     lipid.setScore(1);
     lipid.setDescrCorrect("Contains [M-H+(CH3COONa)]-, ");
     lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
 end
