package rules.positive;

import ceu.biolab.cmm.shared.dto.FeatureAnnotation.AnnotatedFeature;
import ceu.biolab.cmm.shared.dto.FeatureAnnotation.ResultItem;
import ceu.biolab.cmm.shared.domain.MobilePhases;
import java.util.List;

// Declare the global list
global AnnotatedFeature lipid;
global List mobilePhases;
global String sampleType;


rule "Chol_PositiveCheck - Presence [M+H]+"
when
    $adduct: ResultItem(adductName == "[M+H]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end
rule "Chol_PositiveCheck - No presence [M+NH4]+"
when
    not ResultItem(adductName == "[M+NH4]+")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.NH4)
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+NH4]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "Chol_PositiveCheck - Presence [M+NH4]+"
when
    $adduct: ResultItem(adductName == "[M+NH4]+")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.NH4)
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+NH4]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "Chol_PositiveCheck - Presence [cholestadiene ion]+"
when
    $adduct: ResultItem(adductName == "[C27H44]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [cholestadiene ion]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end



rule "Chol_PositiveCheck - Intensity [M+NH4]+ > [M+H]+"
when
    $adduct1: ResultItem(adductName == "[M+NH4]+")
    $adduct2: ResultItem(adductName == "[M+H]+")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.NH4)

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+NH4]+ > [M+H]+, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Chol_PositiveCheck - Intensity [M+NH4]+ < [M+H]+"
when
    $adduct1: ResultItem(adductName == "[M+NH4]+")
    $adduct2: ResultItem(adductName == "[M+H]+")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.NH4)

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+NH4]+ < [M+H]+, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end