package rules.positive;

import ceu.biolab.cmm.shared.dto.FeatureAnnotation.AnnotatedFeature;
import ceu.biolab.cmm.shared.dto.FeatureAnnotation.ResultItem;
import ceu.biolab.cmm.shared.domain.MobilePhases;
import java.util.List;

// Declare the global list
global AnnotatedFeature lipid;
global List mobilePhases;
global String sampleType;

rule "LPE_OP_PositiveCheck - Presence [M+H]+"
when
    $adduct: ResultItem(adductName == "[M+H]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end
rule "LPE_OP_PositiveCheck - No presence [M+H]+"
when
    not ResultItem(adductName == "[M+H]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+H]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "LPE_OP_PositiveCheck - Presence [M+Na]+"
when
    $adduct: ResultItem(adductName == "[M+Na]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+Na]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "LPE_OP_PositiveCheck - Presence [M+K]+"
when
    $adduct: ResultItem(adductName == "[M+K]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+K]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "LPE_OP_PositiveCheck - Presence [M+C2H7N2]+"
when
    $adduct: ResultItem(adductName == "[M+C2H7N2]+")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.NH4)
    $phase2 : MobilePhases() from mobilePhases
    eval($phase2 == MobilePhases.CH3CN)
    $phase3 : MobilePhases() from mobilePhases
    eval($phase3 == MobilePhases.CH3OH)
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+C2H7N2]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end


rule "LPE_OP_PositiveCheck - Presence [M+H-H2O]+"
when
    $adduct: ResultItem(adductName == "[M+H-H2O]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H-H2O]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end
