package rules_id_lipid_expert_knowledge.positive;

import ceu.biolab.cmm.shared.dto.FeatureAnnotation.AnnotatedFeature;
import ceu.biolab.cmm.shared.dto.FeatureAnnotation.ResultItem;
import ceu.biolab.cmm.shared.domain.MobilePhases;
import java.util.List;

// Declare the global list
global AnnotatedFeature lipid;
global List mobilePhases;
global String sampleType;

rule "PE_PositiveCheck - Presence [M+H]+"
when
    $adduct: ResultItem(adductName == "[M+H]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end
rule "PE_PositiveCheck - No presence [M+H]+"
when
    not ResultItem(adductName == "[M+H]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+H]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "PE_PositiveCheck - Presence [M+Na]+"
when
    $adduct: ResultItem(adductName == "[M+Na]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+Na]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "PE_PositiveCheck - Presence [M+K]+"
when
    $adduct: ResultItem(adductName == "[M+K]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+K]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "PE_PositiveCheck - Presence [M+C2H7N2]+"
when
    $adduct: ResultItem(adductName == "[M+C2H7N2]+")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.NH4)
    $phase2 : MobilePhases() from mobilePhases
    eval($phase2 == MobilePhases.CH3CN)
    $phase3 : MobilePhases() from mobilePhases
    eval($phase3 == MobilePhases.CH3OH)
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+C2H7N2]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end




rule "PE_PositiveCheck - Intensity [M+H]+ > [M+Na]+"
when
    $adduct1: ResultItem(adductName == "[M+H]+")
    $adduct2: ResultItem(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+H]+ > [M+Na]+, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "PE_PositiveCheck - Intensity [M+H]+ < [M+Na]+"
when
    $adduct1: ResultItem(adductName == "[M+H]+")
    $adduct2: ResultItem(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+H]+ < [M+Na]+, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end