//Dummy example for positive polarity rule file

package rules_id_lipid_expert_knowledge.negative.userFiles;

import ceu.biolab.cmm.shared.dto.FeatureAnnotation.AnnotatedFeature;
import ceu.biolab.cmm.shared.dto.FeatureAnnotation.ResultItem;
import ceu.biolab.cmm.shared.domain.MobilePhases;
import java.util.List;

// Declare the global list
global AnnotatedFeature lipid;
global List mobilePhases;
global String sampleType;

// =======================================
// RULE TYPE 1: Positive presence
// Check that specific adducts appear
// =======================================
rule "Dummy_Negative - Presence [M-H]-"
when
    $adduct: ResultItem(adductName == "[M-H]-")
    // This checks whether the biological matrix is what's expected
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M-H]-, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "Dummy_Negative - Presence [M+CH3COO]-"
when
    $adduct: ResultItem(adductName == "[M+CH3COO]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.CH3COO)
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+CH3COO]-, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

// =======================================
// RULE TYPE 2: Negative presence (absence)
// Check if most intense adduct does NOT appear
// =======================================
rule "Dummy_Negative - No presence [M+CH3COO]-"
when
    not ResultItem(adductName == "[M+CH3COO]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.CH3COO)
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+CH3COO]-, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

// =======================================
// RULE TYPE 3: Correct intensity order
// Adduct1 intensity > Adduct2 intensity
// =======================================
rule "Dummy_Negative - Intensity [M+CH3COO]- > [M-H]-"
when
    $adduct1: ResultItem(adductName == "[M+CH3COO]-")
    $adduct2: ResultItem(adductName == "[M-H]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.CH3COO)
    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then

    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+CH3COO]- > [M-H]-, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

// =======================================
// RULE TYPE 4: Incorrect intensity order
// Adduct1 intensity < Adduct2 intensity
// =======================================
rule "Dummy_Negative - Intensity [M+CH3COO]- < [M-H]-"
when
    $adduct1: ResultItem(adductName == "[M+CH3COO]-")
    $adduct2: ResultItem(adductName == "[M-H]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.CH3COO)
    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+CH3COO]- < [M-H]-, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end